default_platform(:ios)

platform :ios do
  desc "Build and export signed ipa for CI"
  lane :build do
    build_app(
      scheme: "App",
      workspace: "ios/App/App.xcworkspace",
      export_method: ENV['EXPORT_METHOD'] || "app-store",
      output_directory: "ios-output",
      clean: true
    )
  end
end
