name: Simple Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build web app
      run: |
        npm run build
        ls -la

    - name: Prepare www directory
      run: |
        mkdir -p www
        # Copy from dist if it exists
        if [ -d "dist" ]; then
          cp -r dist/* www/
          echo "Copied from dist/"
        fi
        # Also copy .vite/renderer if it exists
        if [ -d ".vite/renderer" ]; then
          cp -r .vite/renderer/* www/
          echo "Copied from .vite/renderer/"
        fi
        echo "Contents of www directory:"
        ls -la www/

    - name: Sync Capacitor
      run: |
        npx cap sync android
        echo "Capacitor sync complete"

    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace
        echo "APK build complete"

    - name: List APK files
      run: |
        find android -name "*.apk" -type f -exec ls -la {} \;

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MedManager-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
