name: Test Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps --force
        
    - name: List installed packages
      run: npm list --depth=0

    - name: Build web app
      run: |
        npm run build
        
    - name: List build output
      run: |
        ls -la
        ls -la dist/ || echo "No dist folder"
        ls -la .vite/ || echo "No .vite folder"
        ls -la www/ || echo "No www folder"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          dist/
          .vite/
          www/
